/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.acme.kafka.outbox.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class EventKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2068858159938825509L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EventKey\",\"namespace\":\"com.acme.kafka.outbox.avro\",\"fields\":[{\"name\":\"eventId\",\"type\":\"string\"}],\"connect.name\":\"com.acme.kafka.outbox.avro.EventKey\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EventKey> ENCODER =
      new BinaryMessageEncoder<EventKey>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EventKey> DECODER =
      new BinaryMessageDecoder<EventKey>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<EventKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<EventKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EventKey>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this EventKey to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a EventKey from a ByteBuffer. */
  public static EventKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence eventId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EventKey() {}

  /**
   * All-args constructor.
   * @param eventId The new value for eventId
   */
  public EventKey(java.lang.CharSequence eventId) {
    this.eventId = eventId;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventId = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public java.lang.CharSequence getEventId() {
    return eventId;
  }

  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(java.lang.CharSequence value) {
    this.eventId = value;
  }

  /**
   * Creates a new EventKey RecordBuilder.
   * @return A new EventKey RecordBuilder
   */
  public static com.acme.kafka.outbox.avro.EventKey.Builder newBuilder() {
    return new com.acme.kafka.outbox.avro.EventKey.Builder();
  }

  /**
   * Creates a new EventKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EventKey RecordBuilder
   */
  public static com.acme.kafka.outbox.avro.EventKey.Builder newBuilder(com.acme.kafka.outbox.avro.EventKey.Builder other) {
    return new com.acme.kafka.outbox.avro.EventKey.Builder(other);
  }

  /**
   * Creates a new EventKey RecordBuilder by copying an existing EventKey instance.
   * @param other The existing instance to copy.
   * @return A new EventKey RecordBuilder
   */
  public static com.acme.kafka.outbox.avro.EventKey.Builder newBuilder(com.acme.kafka.outbox.avro.EventKey other) {
    return new com.acme.kafka.outbox.avro.EventKey.Builder(other);
  }

  /**
   * RecordBuilder for EventKey instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EventKey>
    implements org.apache.avro.data.RecordBuilder<EventKey> {

    private java.lang.CharSequence eventId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.acme.kafka.outbox.avro.EventKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing EventKey instance
     * @param other The existing instance to copy.
     */
    private Builder(com.acme.kafka.outbox.avro.EventKey other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'eventId' field.
      * @return The value.
      */
    public java.lang.CharSequence getEventId() {
      return eventId;
    }

    /**
      * Sets the value of the 'eventId' field.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public com.acme.kafka.outbox.avro.EventKey.Builder setEventId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.eventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventId' field.
      * @return This builder.
      */
    public com.acme.kafka.outbox.avro.EventKey.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EventKey build() {
      try {
        EventKey record = new EventKey();
        record.eventId = fieldSetFlags()[0] ? this.eventId : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EventKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<EventKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EventKey>
    READER$ = (org.apache.avro.io.DatumReader<EventKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
